# Database Configuration
DB_HOST: localhost
DB_PORT: 5432
DB_USER: postgres
DB_NAME: we_management

# Server Configuration
SERVER_PORT: 8080
SERVER_MODE: debug # debug or release

# Logging Configuration
LOG_LEVEL: debug # debug, info, warn, error
LOG_FORMAT: json # json or text

# CORS Configuration
CORS_ALLOWED_ORIGINS:
  - http://localhost:3000
  - http://localhost:5173

# Rate Limiting
RATE_LIMIT_REQUESTS: 100
RATE_LIMIT_DURATION: 60 # in seconds

# JWT Configuration
JWT_EXPIRATION: 24 # in hours
