version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=we_management
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - we-network

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=we_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - we-network

volumes:
  postgres_data:

networks:
  we-network:
    driver: bridge 